#!/usr/bin/expect -f

set timeout -1
set port [lindex $argv 0];
spawn ./client 127.0.0.1 $port
match_max 100000
set NUM 1

while { $NUM <= 100 } {
	expect "In*"
	send -- "set bar$NUM=barbar\r"
	expect "Out*"
	sleep 0.1
	send -- "get bar$NUM\r"
	expect "Out*"
	sleep 0.1
	send -- "set foo$NUM=foofoo\r"
	expect "Out*"
	sleep 0.1
	send -- "get foo$NUM\r"
	expect "Out*"
	sleep 0.1
	set NUM [ expr $NUM + 1 ]
}
sleep 0.3	
send "\x04"
